name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Update floating major & minor tags
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          # Extract major version (e.g., v1)
          MAJOR=$(echo $TAG | cut -d. -f1)
          # Extract minor version (e.g., v1.1)
          MINOR=$(echo $TAG | cut -d. -f1,2)
          
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Force update major tag (e.g. v1)
          git tag -fa $MAJOR -m "Update $MAJOR to $TAG"
          git push origin $MAJOR --force
          
          # Force update minor tag if it is different from major tag (e.g. v1.1)
          if [ "$MAJOR" != "$MINOR" ]; then
            git tag -fa $MINOR -m "Update $MINOR to $TAG"
            git push origin $MINOR --force
          fi

      - name: BlamLess Retry
        if: failure()
        uses: nirjxr26/BlamLess@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
