name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Update floating major tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          MAJOR=$(echo $TAG | cut -d. -f1)
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag -fa $MAJOR -m "Update $MAJOR to $TAG"
          git push origin $MAJOR --force

      - name: blamless retry
        if: failure()
        uses: nirjxr26/blamless@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
